version: "2"
services:
  dash:
    build: ./dash
    links:
      - app
    ports:
      - "80:8000"
    depends_on:
      - app
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: employee
      MYSQL_USER: regular
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - '3306:3306'